### PR TITLE
Add some missing addon screenshots

### PR DESCRIPTION
**Pull request by Samq64**
Adds screenshots for:
- `custom-menu-bar`
- `editor-compact`
- `editor-square-inputs`
- ~`place-backpack-code-at-cursor`~
- `preview-project-description`
- `reorder-custom-inputs`
- `hide-backpack`
- `download-button`
- `big-save-button` (Taken on https://github.com/ScratchAddons/ScratchAddons/pull/7349)

All of them are 800x600. Also removes the screenshot for `tutorials-button`.

### CODE REVIEW

**Comment by Waakul** [comment]
> For `place-backpack-code-at-cursor`, it might be better to show the backpack item being dragged as well, like this: image
> 
> (I made this screenshot by:)
> 
> * Taking a high quality screenshot of the script
> * In TurboWarp, setting the stage size to 800x600, uploading the screenshot as a costume and entering the costume editor, then setting the costume editor zoom to 100%
> * Adding a bit of CSS to make the dragged backpack item bigger (`<style>[class*="drag-layer"] > * {transform: scale(2);}</style>`)
> * Dragging the backpack item onto the costume in the costume editor canvas (The stage, for some reason, downscales the displayed image on my 1366x768 screen even at full stage size mode, making it look bad)
> * Taking a screenshot with the cursor visible _(EDIT: I just realized the cursor is at normal size in this image)_, then overlaying part of it on the original script image

**nerds making edited screenshot:**
Taking a high quality screenshot of the script
In TurboWarp, setting the stage size to 800x600, uploading the screenshot as a costume and entering the costume editor, then setting the costume editor zoom to 100%
Adding a bit of CSS to make the dragged backpack item bigger (<style>[class*="drag-layer"] > * {transform: scale(2);}</style>)
Dragging the backpack item onto the costume in the costume editor canvas (The stage, for some reason, downscales the displayed image on my 1366x768 screen even at full stage size mode, making it look bad)
Taking a screenshot with the cursor visible (EDIT: I just realized the cursor is at normal size in this image), then overlaying part of it on the original script image
**normal people going the easier way:**
*uses a free vector software like figma*

**Review by Hans5958 — APPROVED** [review]
Looks good. I will merge this tommorow if there are no exceptions.

**Comment by Samq64** [comment]
I know I should have done it earlier but could I bundle the 1.37 images in the PR too?

**Comment by Hans5958** [comment]
Related: #4

**Pull request merged**
