### PR TITLE
Blog

### LINKED ISSUE #3: Add blog feature
Self-explanatory.

Related: Hans5958/ScratchAddons-Website-Hugo#3

### PR DESCRIPTION
**Pull request by TheColaber**
Resolves #3

Mostly work of GrahamSH

### CODE REVIEW

**Comment by GrahamSH-LLK** [comment]
@TheColaber Can we have some screenshots? Is this fully tested?

**Comment by TheColaber** [comment]
Yes fully tested...
image

image

**Comment by TheColaber** [comment]
@GrahamSH-LLK I'm not a fan of everything being centered in a blog

**Comment by TheColaber** [comment]
Yeah I liked how it was before

**Comment by GrahamSH-LLK** [comment]
> Yeah I liked how it was before

Nah, it was kinda ugly

**Comment by TheColaber** [comment]
Idk... @Hans5958 ?

**Comment by Hans5958** [comment]
I'm planning to rewrite this in the future. Something that is close to the Docs style.

**Comment by Hans5958** [comment]
#159, everybody!

**Pull request closed without merging**
