### PR TITLE
Refresh of index page

### PR DESCRIPTION
**Pull request by Hans5958**
**EDIT**: This preview is outdated, please check the latest image.

Was going to update the description/mission statement, but then had an idea on do a revamp of it. Let me know what you think.

Untitled

### CODE REVIEW

**Comment by Hans5958** [comment]
A little bit changes, now with a static hero page, with the slide images on the bottom. I have to consider the circumstances when it needs updating. Probably a better one would be the settings page, but what do you guys think?

image

**Comment by WorldLanguages** [comment]
I like the "hero image". It's easy on the eyes and users immediately understand that we're (mainly) a browser extension. And I like that my eye only has to focus on a specific part of the image.
I would consider highlighting more than 1 enabled addon. Possibly 2 enabled and the last one disabled (to be considered - the popup does not show disabled addons and that could confuse users).

**Comment by WorldLanguages** [comment]
Would also be great if clicking "load more" did smooth-scrolling instead of abruptly sending you to the "features" section.

**Comment by Secret-chest** [comment]
I think we should show more images, but not scroll them automatically.

**Comment by Hans5958** [comment]
> we should show more images, but not scroll them automatically.

User may miss the images if it isn't automatically scroll. Don't worry, it would stop if someone interacts with it (which is still the current behavior live on the site)

**Comment by Hans5958** [comment]
TODO (In case anyone want to pick this up)

- [ ] Do a better mockup. We can update the dummy browser to be something more... newer. Original .svg attatched:
   intro hero image

**Comment by Samq64** [comment]
Do a better mockup. We can update the dummy browser to be something more... newer. Original .svg

Maybe the popup could also show a few more addons?

**Comment by Hans5958** [comment]
> Maybe the popup could also show a few more addons?

Oh, yes, of couse, it's just an example.

**Comment by Hans5958** [comment]
Got time around to update the hero image. While the browser is still... that, I tried to tidy up it, while updating the images and add the Scratch website (blurred in case of problems, and to divert focus to the extension). This should make it ready to merge.

**Comment by Secret-chest** [comment]
I don't like the blur, it is disrupting and the Scratch screenshot is vanilla anyways.

**Review by WorldLanguages — APPROVED** [review]

**Comment by WorldLanguages** [comment]
Looks very nice!

If I could change one more thing about the landing page, it would probably be the `Satisfied? Don't hesitate to install it now!` phrase. It doesn't really it our website, I think.

**Comment by Hans5958** [comment]
What do you mean by "doesn't really it"? 

Also, any ideas? I think I would remove the "Satisfied?" part first, but I would leave it as-is for now.

**Comment by BroJac5246** [comment]
> Looks very nice!
> 
> If I could change one more thing about the landing page, it would probably be the `Satisfied? Don't hesitate to install it now!` phrase. It doesn't really fit our website, I think.

Just want to add that this coincidentally occurred to me today as well; it looks out-of-place and is somewhat unprofessional.

**Pull request merged**
