### PR TITLE
New page: extension-settings

### PR DESCRIPTION
**Pull request by WorldLanguages**
According to Google Search console data, the number of users that google "scratch addons settings" is considerable. I had the idea of making a page called "scratch addons settings" that can get number 1 on search results to help those users find the settings page.

This is a new page that shows users how to access the settings page. For Chromium users, if Scratch Addons stable version is running, the user is redirected to the settings page automatically.
If the user isn't redirected, the same steps as welcome.html are shown.
Maybe we could also add an "install" button below the steps in case the user doesn't have SA installed.

image

@Hans5958 Is there a way to reuse the strings from welcome.html on this file so that they don't need to be translated again? And I would like your opinion on the existence of this page too.

### CODE REVIEW

**Comment by Hans5958** [comment]
Try to use {{ T [string key] }}. I remember I made them work, along with the fact that it won't mess up in TX.

**Comment by apple502j** [comment]
LGTM.

> To be honest, I rather have this as a FAQ entry than a singular page. Seems like a lowly attempt to attract users, eh?
@Hans5958 This auto-redirects user to the real settings on Chrome, so having a dedicated page is better.

**Comment by Hans5958** [comment]
W_L has told me about that, actually. At least that's my first impression of it.

**Comment by WorldLanguages** [comment]
> > Is there a way to reuse the strings from welcome.html on this file so that they don't need to be translated again?
> 
> ~Try to use {{ T [string key] }}. I remember I made them work, along with the fact that it won't mess up in TX.~ Oh, you say from welcome.html. I don't think so.

@Hans5958 Could this be merged? I think we enabled "translation memory" on Transifex, so this isn't an issue anymore.

**Comment by Hans5958** [comment]
Go ahead and merge it. Shouldn't you change the filename though? `scratchaddons.com/scratch-addons-settings` seems off, tho.

**Comment by WorldLanguages** [comment]
@Hans5958 What do you think it should be?
Btw it looks like I messed up the conflict resolution so this can't be merged yet lol, `this branch cannot be rebased due to conflicts`

**Comment by Hans5958** [comment]
`settings

**Comment by Hans5958** [comment]
Maybe just `settings`, or `sa-settings`?

**Comment by WorldLanguages** [comment]
Looks like I'll need to fight with git in the terminal to resolve the rebase conflicts

**Comment by Hans5958** [comment]
I did some rebase so now it should work.

**Comment by WorldLanguages** [comment]
@Hans5958 Can I squash and merge?

**Comment by mxmou** [comment]
> Maybe just `settings` or `sa-settings`?

`extension-settings`?

**Comment by Hans5958** [comment]
> @Hans5958 Can I squash and merge?

Rebase now works, but anything works for me.

**Comment by WorldLanguages** [comment]
Looks like the Google crawler isn't showing this page on search results because it follows the redirect for some reason (`Failed: Redirect error`)

**Pull request merged**
