### PR TITLE
Fix .site.IsServer deprecation error

### PR DESCRIPTION
**Pull request by Samq64**
I thought this was already fixed?

### CODE REVIEW

**Comment by Samq64** [comment]
The action's version is too old. Should I update the action or downgrade on my end?

**Comment by Hans5958** [comment]
I'd rather have the Hugo version updated. Don't worry if it fails here, just in case. If the deployment works on this PR, it would also work on master.

**Comment by Samq64** [comment]
I'm asking because of
> Starting on Hugo 0.120, the minify command works differently to the point that it can't escape quotation marks properly, which makes the feedback system break. This should be investigated further, but this is good enough patch for now.

**Comment by Hans5958** [comment]
Problem is that v0.120 is been a while. The current version is v0.133. Something may change. I would test it, or you can test it too.

**Comment by Hans5958** [comment]
I checked using v0.134, it seems that they have fixed it. You can update it safely.

**Review by Hans5958 — APPROVED** [review]
Dang, I was confused between v0.133 and v0.134. I was correct on v0.133 last time!

By the way, thanks for the help!

**Comment by Samq64** [comment]
You're welcome and I'm a little confused too since the console message said 0.134.

**Pull request merged**
