### PR TITLE
Create blog post for v1.34

### LINKED ISSUE #365: Blog post for v1.34
I'm up for writing the blog post for the next update when you're ready. I've actually been working on a draft already.

Ideas are welcome.

For the compact editor feature, I came up with the heading "a throwback to Scratch 2.0". Like it?

### PR DESCRIPTION
**Pull request by DNin01**
Resolves #365

Adds a blog post for the next release.

To be merged after the update is available.

### CODE REVIEW

**Review by Hans5958 — APPROVED** [review]
Looks good in a glimpse.

Just a suggestion: Can you try adding a cover image for this post? ([see docs on how to set the cover image](https://github.com/ScratchAddons/website-v2/wiki/Custom-front-matter-variables#cover_image))

**Comment by WorldLanguages** [comment]
Looks good to me

**Comment by DNin01** [comment]
> Looks good in a glimpse.
> 
> Just a suggestion: Can you try adding a cover image for this post? ([see docs on how to set the cover image](https://github.com/ScratchAddons/website-v2/wiki/Custom-front-matter-variables#cover_image))

Have we ever set a cover image for a blog post before? That would be so cool.

I'm you're looking for something closer to the YouTube video thumbnails, I don't really have the tools right now. Maybe someone else could become the cover image artist?

I did come up with this image as a base:
Block with up-down arrow buttons

**Comment by Samq64** [comment]
> Have we ever set a cover image for a blog post before? That would be so cool.

He recommended it on my blog post PR but for some reason I understand exactly what he meant at the time.

**Comment by DNin01** [comment]
> for some reason I understand exactly what he meant at the time.

You did or you didn't?

**Comment by Samq64** [comment]
> > for some reason I understand exactly what he meant at the time.
> 
> You did or you didn't?

I added an image but it wasn't a cover image.

**Comment by Hans5958** [comment]
> Have we ever set a cover image for a blog post before?

No, and I wanted a post to start doing it, I guess.

**Comment by DNin01** [comment]
I think you forgot to reset the date again. This time it's not as big a deal, though, it's only a few days off.

**Comment by DNin01** [comment]
Anyway, 🎉

**Comment by Hans5958** [comment]
> I think you forgot to reset the date again. This time it's not as big a deal, though, it's only a few days off.

I've fixed it on 077c9405bb954df994e77d1f78334fd16530300e

**Comment by WorldLanguages** [comment]
Thanks!

**Pull request merged**
