### PR TITLE
New images for addons

### PR DESCRIPTION
**Pull request by OregSamSas**
Related issue: #4 
Added four new images. Sorry I couldn't come up with better ideas :(
This PR infringe all the rules of taking screenshots of addons.

Changes:

1. `default-project`: I can remove the borderlines, the mouse pointer and the screenshot-fragment in the bottom

The following images are done by taking a screenshot from the feature that the addon removes (or restricts)/bug that fixes the addon, the cross that out (very bad solution, so I propose these just in the case, if any type of images are welcom now for completing the list of all of the addons)

2. `disable-autosave`: I can make it not centered, so the "save project" button will be in the top, and the browser searchbar won't be on the image
3. `disable-stage-drag-select`: I can cross it out with only one line, if that looks better
4. <strike><code>fix-uploaded-svgs</code></strike></hmtl> 
5. `remove-search-bar-autocomplete `
6. `sprite-properties`

### CODE REVIEW

**Comment by OregSamSas** [comment]
I have other versions of images:

<details>
<summary><code>default-project</code>:</summary>
default-project2
</details>
<details>
<summary><code>disable-autosave</code>:</summary>
disable-auto-save2
</details>
<details>
<summary><code>disable-autosave</code>:</summary>
disable-stage-drag-select2
</details>
<details>
<summary><code>disable-autosave</code>:</summary>
fix-uploaded-svgs2

It's just worse :(
</details>

**Comment by RedGuy12** [comment]
The bugs `fix-uploaded-svgs` fixes do not make the Scratch renderer crash.

**Comment by OregSamSas** [comment]
> The bugs `fix-uploaded-svgs` fixes do not make the Scratch renderer crash.

Didn't know that, I'm so sorry. Should I remove the file bc it doesn't have an own commit, so you can't ignore it on merging, or you still can notmerge it?

**Comment by Hans5958** [comment]
I'm up of red crosses (if there is no alternative), but it seems that the image quality is quite bad. Could you try again?

**Comment by OregSamSas** [comment]
> I'm up of red crosses...

<html>
<p> Does it mean something like this:  If so, I'd feel myself happy. But I thought it could mean the opposite as well.</p>
</html>

> but it seems that the image quality is quite bad. Could you try again?

Of course, I can try it again but it will take some time. Until then I might come up with other image ideas too.

> please remove fix-uploaded-svgs image

I shall remove it don't worry.

> I have other versions of images...

Furthermore, I wanted to ask you about which version do you prefer of the first and only (at least a bit) proper and good-looking image? (I mean this one: `default-project`)

Sorry for answering lately.

**Comment by Hans5958** [comment]
> Does it mean something like this: ...

Yes. I can rephrase it as "I think having red crosses is a good idea,..."

> Of course, I can try it again but it will take some time. Until then I might come up with other image ideas too.

Take your time, man. No rush.

**Comment by Hans5958** [comment]
I got some time around to think about the red cross. I thinki we should have the simple cross without being stretched, like this.

https://api.iconify.design/maki:cross-11.svg



Not wide, not tall, you can fit it in a square. Any kind of cross and color would work, just mind the aspect ratio.

**Comment by OregSamSas** [comment]
> I got some time around to think about the red cross. I thinki we should have the simple cross without being stretched, like this.

OK, I edit them with this 1:1 cross right away.

With other images, I stuck to the simplest versions, but I have other variants which may look more developed, but more crowded as well, and edited multiple times.

Alternative versions can be viewed here:
[#1 (comment)](https://github.com/ScratchAddons/website-v2/pull/245#issuecomment-1222770696)

**Comment by OregSamSas** [comment]
Do they look better, or did you think of something else?

**Comment by Hans5958** [comment]
I would say to avoid having the additional "Say goodbye to autosave" section of the `disable-autosave` section.

**Comment by OregSamSas** [comment]
> I would say to avoid having the additional "Say goodbye to autosave" section of the `disable-autosave` section.

The problem is, I don't know what to put there. Probably leave it blank, but then it would look strange, in my opinion, because then the main part of the image is aligned to the top. Other method is to include in the image a bit of the browser's navbar in the image and then the x mark would be centred.

**Comment by Hans5958** [comment]
I can see that. I would say that it is fine to have the awkward empty buttom. I guess if it is difficult, you can do put it on the center and either do one of the following.
1. incorporate the browser interface (see [editor-sounds](https://scratchaddons.com/assets/img/addons/editor-sounds.png))
2. left it empty (at least it is balanced)
3. fill the top empty part with the same blue of the taskbar

**Review by Hans5958 — APPROVED** [review]
For now I think it is fine to merge. Anyone who wanted to update may do as their wish.

**Pull request merged**
