### PR TITLE
Revamp changelog page

### LINKED ISSUE #53: Revamp changelog page
I forgot to create this issue on the last batch, so here it is.

- Revamp design of the page
- Add highlights based on the extension
- Make it translatable (partially, not including the entries and highlights)

Some of this are already done on the [`changelog`](https://github.com/ScratchAddons/website-v2/tree/changelog) branch. To whom it may concern, please avoid creating a PR of it in the meantime.

### PR DESCRIPTION
**Pull request by Hans5958**
Resolves #53 

For those who wanted to give their final opinions, here's the PR before I merge things off. A lot of things have been changed since the last update. Keep in mind that this will make the changelog workflow obsolete, which means manual update is required, for now. Other stuff also have been changed for completeness sake.

For now, I have decided to not translate both the highlights and the entries.

If there are no more concerns, I will merge this in the next twelve hours.

image

### CODE REVIEW

**Comment by mxmou** [comment]
The card with the video looks like it should have some padding on the left.

**Comment by RedGuy12** [comment]
The links section looks out of place. I say it should be simply

GitHub release • Source code • New commits

with no header.
(Maybe italicized too?)
________________________________
From: Hans5958 ***@***.***>
Sent: Tuesday, June 22, 2021 10:55:13 AM
To: ScratchAddons/website-v2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/website-v2] Revamp changelog page (#68)


Resolves #53<https://github.com/ScratchAddons/website-v2/issues/53>

For those who wanted to give their final opinions, here's the PR before I merge things off. A lot of things have been changed since the last update. Keep in mind that this will make the changelog workflow obsolete, which means manual update is required, for now. Other stuff also have been changed for completeness sake.

For now, I have decided to not translate both the highlights and the entries.

If there are no more concerns, I will merge this in the next twelve hours.

[image]<https://user-images.githubusercontent.com/11584103/122957831-84c0de00-d3ac-11eb-96a7-df7de9bbbc92.png>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/ScratchAddons/website-v2/pull/68

Commit Summary

  *   First batch of changes
  *   Add image alt
  *   Scroll directly to version from versionname query
  *   Remove outdated update changelog workflow
  *   Merge branch 'master' into changelog
  *   Add i18n strings
  *   Update to v1.16.3, rework player modals, localized dates
  *   Anchor links

File Changes

  *   D .github/workflows/update-changelog.yml<https://github.com/ScratchAddons/website-v2/pull/68/files#diff-15d44bf84a03bd4b62871c8cfe5cd7b6298ae5c033a36cee56e357f74199449a> (51)
  *   M assets/assets/css/base.scss<https://github.com/ScratchAddons/website-v2/pull/68/files#diff-d9c6bf25dd35e5794167ddf35f97c1134183244deaede42815cf32a480936d12> (86)
  *   M assets/assets/css/landing.scss<https://github.com/ScratchAddons/website-v2/pull/68/files#diff-0723e913520e0a29978eb74cc07f63aeaded798ea873cf877e4bf79023f6d7f8> (59)
  *   A content/changelog.html<https://github.com/ScratchAddons/website-v2/pull/68/files#diff-66751104290e7a65ba712c4ac187ab6c1602b6f83005ea794c390998a138c992> (48)
  *   D content/changelog.md<https://github.com/ScratchAddons/website-v2/pull/68/files#diff-b5be885132b7a2afe09b2ac5692331579160fd20fdea5bf0f98b7a8a68c5457a> (478)
  *   A data/changelog.yml<https://github.com/ScratchAddons/website-v2/pull/68/files#diff-2de4835928f1a86a4ecdda8860a52a871ff0f309f663d907da91580cde126153> (657)
  *   M i18n/en.yaml<https://github.com/ScratchAddons/website-v2/pull/68/files#diff-d57e09739aebffaedf6e8a1d875a3ffcdc4f168361b3c292f7f7b1665372e4c0> (20)
  *   M layouts/_default/home.html<https://github.com/ScratchAddons/website-v2/pull/68/files#diff-857e28799841562c3cd4bd04671992708f4aafc341988ad1ccc80903e3dc1986> (29)
  *   A layouts/partials/youtube.html<https://github.com/ScratchAddons/website-v2/pull/68/files#diff-ce0e6859bca8c519719ce3d2acdcc3d386aa753649b41b991f96fd7f570636eb> (37)
  *   A layouts/shortcodes/specifics/changelog.html<https://github.com/ScratchAddons/website-v2/pull/68/files#diff-f9e3c39a610640dbc854f22624cd0de89467d239ceb728f7e4f6b167783c72a9> (74)
  *   A layouts/shortcodes/youtube.html<https://github.com/ScratchAddons/website-v2/pull/68/files#diff-fa579c2bd3c9abdfae00c97d78c96928ea45927ddd652aeeed422fbb623376fd> (1)
  *   A static/assets/img/release-highlights/auto-hide-palette.gif<https://github.com/ScratchAddons/website-v2/pull/68/files#diff-6e420fa15af5a457b30b7aec79b8a902411fb6557885469c05e9b3a65f5d793c> (0)
  *   A static/assets/img/release-highlights/catblocks.png<https://github.com/ScratchAddons/website-v2/pull/68/files#diff-e272c9b9fdedab00107ccfd9eeac0a2ede7cfb5d8367bbe78421f788782c639f> (0)
  *   A static/assets/img/release-highlights/copy-comment-link.png<https://github.com/ScratchAddons/website-v2/pull/68/files#diff-6f5847a3491895eed73e5de698c828953d9135391de106d1a51024755b8ee5a2> (0)
  *   A static/assets/img/release-highlights/data-cat-tweaks.png<https://github.com/ScratchAddons/website-v2/pull/68/files#diff-cc9f62bf2fb1bb7e0c6b53c4e6e40d8ec4dd048d6807714a95368ff177648086> (0)
  *   A static/assets/img/release-highlights/draganddrop.gif<https://github.com/ScratchAddons/website-v2/pull/68/files#diff-d4796dee79f1179d0dafe5716bff1f9dd69165cad0e09315679f5b73a6bd90d8> (0)
  *   A static/assets/img/release-highlights/folders.png<https://github.com/ScratchAddons/website-v2/pull/68/files#diff-39b674d52c5710b5e8261251dac778a0af68e79a81383027301cf7ca47bec490> (0)
  *   A static/assets/img/release-highlights/hex-color-picker.png<https://github.com/ScratchAddons/website-v2/pull/68/files#diff-4fabb58a3fa65a0928ec703a6da195e37eb70c8f0e394bfc3190585bc0aa7086> (0)
  *   A static/assets/img/release-highlights/onion.png<https://github.com/ScratchAddons/website-v2/pull/68/files#diff-f5c79caf6e0224f3319117bbe92d65e2886d65b57395d7a3b25c4f81d5428132> (0)
  *   A static/assets/img/release-highlights/project-lovers.png<https://github.com/ScratchAddons/website-v2/pull/68/files#diff-f258cae439737e58224c8c3436f95e648e9ceba544e56bb60ad0956efa82ec5e> (0)
  *   D static/assets/js/landing.js<https://github.com/ScratchAddons/website-v2/pull/68/files#diff-f9cac74f0fb099e8645d36e71ebef0345afeebdfb59f23f3145b3867c9705855> (25)
  *   A static/assets/js/player-modal.js<https://github.com/ScratchAddons/website-v2/pull/68/files#diff-7d10ae67304c8fc58b2c7b2f54f06023bf524ddee7c74883d3a5512a877fdfaa> (34)
  *   M static/assets/js/website-base.js<https://github.com/ScratchAddons/website-v2/pull/68/files#diff-62a028472dc3be3b8de0a370ddc5213ae1e451647da991deb6f90919d40a1925> (13)

Patch Links:

  *   https://github.com/ScratchAddons/website-v2/pull/68.patch
  *   https://github.com/ScratchAddons/website-v2/pull/68.diff

**Comment by Hans5958** [comment]
> 
> 
> The card with the video looks like it should have some padding on the left.

This is intentional due to how the design of cards of Bootstrap. It will make more sense if the highlight image is larger.

image
image
image

Making it shorter doesn't look nice, making it longer by giving it additional margin also doesn't look nice, so I decided not to intervene on this one.

> The links section looks out of place. I say it should be simply
>
> GitHub release • Source code • New commits
>
> with no header.
> (Maybe italicized too?)

My plans are we can add more links if we wanted to. Having it on a dot separated text won't look nice with this case.

**Comment by Hans5958** [comment]
Forgot to write some features on this PR

1. Simple element ID and anchoring (#1.16.3 is the ID for 1.16.3 section)
2. Support for `versionname` query (will go straight into it)
3. Badges to indicate latest and yanked release
4. Localised dates
5. Support for highlights (that one that appeared on the extension update modal, supports image, text only, and YouTube, may expand later)
6. Revamped player modal
7. Additional links, and ability to add more links to the list

**Pull request merged**
