### PR TITLE
Add redirect pages

### PR DESCRIPTION
**Pull request by Hans5958**
Superseded: #121  
Related: #270

This PR adds redirect pages, which all of it is placed inside a folder, but then can be accessed using without the prefix `/redirect/...`.

Supported pages:
- `/chrome`
- `/discord-dev`
- `/discord`
- `/download-source`
- `/edge`
- `/firefox`
- `/install` (moved inside the folder)
- `/repo`
- `/transifex`
- `/youtube`

### CODE REVIEW

**Comment by WorldLanguages** [comment]
Nice!

Some more suggestions:
- `/org`, `/gh-organization`, `/github` or similar (would redirect to github.com/scratchaddons)
- `/analytics` (would redirect to analytics.scratchaddons.com)
- `/twitter` (and `/reddit` I guess, even tho I don't think we should have an official subreddit)
- `/settings` should be an alias of already existing `/extension-settings` (this route is redirected through a Cloudflare page rule as of now)
- `/forumposts` should redirect to https://ocular.jeffalo.net/search?q=%22no%20flash%20versions%20detected%22&sort=newest (this is already a Cloudflare redirect available at `/_ua`)

**Comment by Hans5958** [comment]
Did these redirects.

- `/analytics`
- `/forum-posts` and `/_ua` (_ua is the primary alias)
- `/github`
- `/reddit`
- `/settings`

**Review by WorldLanguages — APPROVED** [review]
LGTM

Please remind me to remove Cloudflare page rules after this is merged

**Comment by WorldLanguages** [comment]
Removed CloudFlare page rules.

**Pull request merged**
