### PR TITLE
Show exact user count on website

### LINKED ISSUE #102: [Suggestion] Show exact user count somewhere in the website (maybe front page)
Chrome Web Store is stuck in multiples of 10,000 but the exact user count is still available as an HTML comment in the normal store page:
image
And Firefox Add-Ons has visible exact counts in the store page.
We could add these numbers together and show the result somewhere.
And possibly with [odometer](https://github.hubspot.com/odometer/docs/welcome/) :P

### PR DESCRIPTION
**Pull request by TheColaber**
@WorldLanguages you can change the html and put the count where you want it

@Hans5958 no idea how to localize this.

Resolves #102

### CODE REVIEW

**Comment by WorldLanguages** [comment]
Honestly I'm not convinced about the position of the user count, I wanted a big one below the highlights, but I'm biased :P

**Comment by TheColaber** [comment]
I agree, which is why I said
> @WorldLanguages you can change the html and put the count where you want it

**Comment by GrahamSH-LLK** [comment]
Odometer is archived, maybe find a new lib?

**Comment by WorldLanguages** [comment]
usercount.json broke because the Chrome Web Store removed public user counts :C

**Comment by TheColaber** [comment]
WL will now change the value by hand.

**Review by Hans5958 — DISMISSED** [review]
WL asked me for approval. But, "xxx,xxx Users"? Not "xxx,xxx users"?

**Comment by Hans5958** [comment]
See `Global.InstallFor` to see what I mean. I would suggest doing that, but since you guys need to do odometer, do something like `IndexPage.Highlights.Paragraph`.

**Review by Hans5958 — APPROVED** [review]
WL had contacted me that he do it top-down like on ScratchStats, so I gave you my full approval.

**Pull request merged**
