### PR TITLE
Make it very clear that we are not the Scratch Team on the feedback page

### PR DESCRIPTION
**Pull request by CST1229**
i am going insane. everyone keeps addressing us as "scratch team", or filling in the username field with the placeholder "ScratchCat", asking us to ban users or unban them or themselves (ok i wrote this in a *sliiiiight* fit of rage)
image

### CODE REVIEW

**Comment by Samq64** [comment]
I suggested this in #439 a while ago and Hans disagreed.

**Comment by Hans5958** [comment]
My point still stands on https://github.com/ScratchAddons/website-v2/issues/439#issuecomment-2089420424. Take a time to read it again.

Perhaps, if I had time, I would convert this into a modal that would really put focus on the message instead. I will open this for the time being.

**Comment by WorldLanguages** [comment]
It's unfortunate that our feedback page has quite good SEO

**Comment by WorldLanguages** [comment]
@CST1229 This probably won't be very effective. Most likely, we rank quite high for "Scratch feedback" on Google, or similar. Meanwhile, most of our users probably go through the "Send Feedback" button on the settings page, instead of search engines.

A better solution is to tell Google not to index /feedback. For those people actually searching for a way to send "Scratch **Addons** feedback", we can allow Google to index a different page/doc that itself provides a link to /feedback. A disclaimer like this could fit there.

**Comment by CST1229** [comment]
superseded by #506

**Pull request closed without merging**
