### PR TITLE
Update addon.* API and manifest docs

### PR DESCRIPTION
**Pull request by WorldLanguages**
Related to #75

- Update addon.auth to current prerelease async implementation
- Update beforeRemixButton sharedSpace info
- Add a note on addon types > persistent scripts, discouraging the creation of addons that rely on them
- Add a list of common terms to manifest docs > description
- Add more info on addon tags, split into 3 tables

### CODE REVIEW

**Comment by WorldLanguages** [comment]
@mxmou I'm adding the list of common words you wrote a few days back to the docs within this PR

**Comment by RedGuy12** [comment]
🎊🎊✨✨🎉🎉


100!!




________________________________
From: World_Languages ***@***.***>
Sent: Tuesday, July 27, 2021 3:42:27 PM
To: ScratchAddons/website-v2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/website-v2] Update addon.* API and manifest docs (#100)


Related to #75<https://github.com/ScratchAddons/website-v2/issues/75>

  *   Update addon.auth to current prerelease async implementation
  *   Update beforeRemixButton sharedSpace info
  *   Add a note on addon types > persistent scripts, discouraging the creation of addons that rely on them
  *   Add a list of common terms to manifest docs > description
  *   Add more info on addon tags, split into 3 tables

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/ScratchAddons/website-v2/pull/100

Commit Summary

  *   Update addon.auth
  *   Update beforeRemixButton sharedSpace
  *   Separate forums spaces from website spaces
  *   Discourage persistent scripts
  *   Manifest docs: add list of common terms for use in description
  *   Manifest docs: add more info on tags
  *   Add missing colons

File Changes

  *   M content/docs/develop/addon-types/persistent-scripts.md<https://github.com/ScratchAddons/website-v2/pull/100/files#diff-e3a6217dfa5cdaa39ea9efefbc4fddf42a3d528bfab1bca858d2c87fee78b0a9> (3)
  *   M content/docs/reference/addon-api/addon.auth.md<https://github.com/ScratchAddons/website-v2/pull/100/files#diff-ecc0db37b226c0de0cdc0519d37ae8389539e70c574023d99d24233bf3413ba2> (70)
  *   M content/docs/reference/addon-api/addon.tab/addon.tab.appendToSharedSpace.md<https://github.com/ScratchAddons/website-v2/pull/100/files#diff-f1c66f75b84f00c8ad24807c604ba86d8c0d7aa5b8d0f28e8208a98a093a8467> (62)
  *   M content/docs/reference/addon-manifest.md<https://github.com/ScratchAddons/website-v2/pull/100/files#diff-b440f8ed7407a43005396e0f0226e251888dd29f65418082f070bc52cc9f8444> (169)

Patch Links:

  *   https://github.com/ScratchAddons/website-v2/pull/100.patch
  *   https://github.com/ScratchAddons/website-v2/pull/100.diff

**Comment by TheColaber** [comment]
Yay 😁 congrats hans

**Comment by RedGuy12** [comment]
lol wl made this not hans



________________________________

**Comment by TheColaber** [comment]
ik, congrats to hans for handling the website so well, so it's mostly because of him that we are here.

**Review by Hans5958 — APPROVED** [review]
WL asked me about i18n. Keep in mind about #89. WL said that we shouldn't worry that though.

Also, thanks for the kind words.

**Pull request merged**
