### PR TITLE
Add missing period

### PR DESCRIPTION
**Pull request by Hans5958**
To be merged when the page needs updated, or maybe if there large enough updates related to the docs. I don't know.

### CODE REVIEW

**Comment by RedGuy12** [comment]
...why can it not be merged now?

**Comment by Hans5958** [comment]
That sentence will need retranslation on TX

**Comment by Hans5958** [comment]
No one says it's hard, I'm just waiting the moment.

**Comment by Hans5958** [comment]
I'll just merge this now since i18n require updating because comments

**Pull request merged**
