### PR TITLE
/chrome to redirect to Chrome Webstore page

### PR DESCRIPTION
**Pull request by LercDsgn**
### Migrated to #121 with more files

### CODE REVIEW

**Comment by CST1229** [comment]
I think this should left to a domain host redirect I think, like _ua.

**Comment by WorldLanguages** [comment]
> I think this should left to a domain host redirect I think, like _ua.

I can't add unlimited page rules without paying, so this is fine.

**Comment by LercDsgn** [comment]
> I can't add unlimited page rules without paying, so this is fine.
Any problems if I add these too?
/github
/localize
/downloadsource
/firefox
/youtube
/discord
/devdiscord

**Comment by LercDsgn** [comment]
I think I should close this now.

**Pull request closed without merging**
