### PR TITLE
Improve images for `editor-comment-previews` and `fullscreen`

### PR DESCRIPTION
**Pull request by lisa-wolfgang**
Improved versions of `editor-comment-previews` and `fullscreen`:

editor-comment-previews

fullscreen

### CODE REVIEW

**Comment by RedGuy12** [comment]
Eh, I feel like the current image for editor-comment-previews is easier to tell what's going on

**Comment by lisa-wolfgang** [comment]
> Eh, I feel like the current image for editor-comment-previews is easier to tell what's going on

@RedGuy12 Here are the two side-by-side:

image
image

There are a number of reasons I prefer this new one:
1. The actual comment preview (what we're trying to showcase) takes up more screen space in the new image.
2. In the original, it's not very clear what is being hovered over. The comment doesn't seem to be attached to anything until you actually go and read the collapsed comment's text and then the comment preview's text. In the new one, it is very clear that the preview involves the custom block because it is visually intersecting with it.
3. The original (at first glance to someone who has never used the addon before) appears to only depict hovering a collapsed comment, which is, in my opinion as the addon's developer, the least interesting feature. The new one simultaneously shows block hovering, custom block definition (JSDoc) support, and block palette support.

**Comment by RedGuy12** [comment]
See, hovering a collapsed comment is the main feature, regardless of whether it’s the most useful. Also, in the block palette it’s unclear where the tooltip content is coming from.

**Comment by lisa-wolfgang** [comment]
Okay, but what about the one for full screen?

**Pull request closed without merging**
