### PR TITLE
Add blog section

### LINKED ISSUE #3: Add blog feature
Self-explanatory.

Related: Hans5958/ScratchAddons-Website-Hugo#3

### PR DESCRIPTION
**Pull request by Hans5958**
I thought I need to do a lot more, but turns out it's just needed little finishing touches, and I think it is finally ready. So sorry for the long overdue.

Maybe if you want we can move some annoucement, but I'll give that to you.

Resolves #3 

**WARNING: Before merging, please remove the test pages, or wait for me to remove those!**

image

image

### CODE REVIEW

**Comment by lisa-wolfgang** [comment]
The tile layout seems a bit weird in my opinion. If we switched to a list, we could also add thumbnails to each post...

Also, many people would appreciate having a way to subscribe to the blog somehow.

**Comment by Hans5958** [comment]
> The tile layout seems a bit weird in my opinion. If we switched to a list, we could also add thumbnails to each post...
> 
> Also, many people would appreciate having a way to subscribe to the blog somehow.

I got two options, between cards like that, or a simple rundown like WordPress. I still think we can do thumbnails on the top of the cards.

Hmm, notifications about the blog... Usually it is done from the outside (people usually do Twitter but ours will be our Discord and YouTube channel). There will be an RSS on https://scratchaddons.com/blog/index.xml, but I don't think this generation of users will use it

**Comment by RedGuy12** [comment]
i use rss feeds lol

**Comment by Hans5958** [comment]
Here's an example for articles with cover images. Should I add another text on the bottom of the text as label or nah? (on the article)

### In the article...
image

### In the index
image

**Comment by Hans5958** [comment]
> I use RSS also chrome wants to bring it back

I see. Again, don't worry since you can subscribe to it.

**Comment by Hans5958** [comment]
Oh, yeah, one important thing. Should I open the whole to be translated?

For now, I'll go to the path of least resistance, which is to leave the blog posts untranslated (the elements like the index title, go back text, etc are translated, but not the posts).

What do you think, guys?

cc @WorldLanguages @apple502j

**Comment by WorldLanguages** [comment]
I think it should stay untranslated for now

**Comment by Hans5958** [comment]
Alright, I did some changes for it.

**Comment by Hans5958** [comment]
Here's the first blog post that I created. If you guys wanted to change, go do so.

## Welcome to our new blog!

Hello, everyone. If you can read this, chances are our blog is now up. Welcome!

We are proud to announce that we got a new blog for Scratch Addons. Currently, this is the only post, but expect updates, tips, and other things in the next days. We can't wait to share them to you, especially with the next version.

Stay tuned with the new posts on our available channels, like YouTube, Discord, etc. We also got [a RSS feed](https://scratchaddons.com/blog/index.xml) if you are  into that sort of thing.

**Comment by Hans5958** [comment]
My plan is to merge this days before the next version, but it seems that I'm going to miss it. I'm going to change it post by removing the mention of the future version.

That being said, I appreciate if people can write blogs, whenever for this first or the future posts.

**Comment by Hans5958** [comment]
I have decided to remove the mention of the next version, but if someone really wanted to give updates for the future version, go ahead,

I will merge this in a short moments.

**Pull request merged**
