### PR TITLE
Add discuss-button page

### PR DESCRIPTION
**Pull request by Samq64**
Adds the customizable navigation bar addon to the docs.

### CODE REVIEW

**Review by Hans5958 — APPROVED** [review]

**Comment by Samq64** [comment]
What is the best way to add somthing to tne gallary? `<figure>`?

**Comment by Hans5958** [comment]
> What is the best way to add something to tne gallery? `<figure>`?

I just realised that I haven't thought about this yet.

Ideally it would be something like the gallery on Wikipedia, but I have to implement it. For now either `` and `` would work. Only concern with `<figure>` is it may be harder for translators to translate, but I think it's fine if you want to try.

**Comment by Samq64** [comment]
I guess it can be done later then.

**Comment by Hans5958** [comment]
I would merge this tommorow, unless you tell me that it wasn't ready, or I simply forgot.

**Pull request merged**
