### PR TITLE
Remove pages and links related to the extension transition

### PR DESCRIPTION
**Pull request by Hans5958**
cc @WorldLanguages

### CODE REVIEW

**Comment by WorldLanguages** [comment]
Related: https://analytics.scratchaddons.com/scratchaddons.com?entry_page=%2Fscratch-messaging-transition%2F&period=30d

**Review by RedGuy12 — APPROVED** [review]
> Maybe I would remove the direct link on /welcome first, what do you think?

That is probably where everyone is coming from, so removing the link will probably remove all the traffic to this page. I say go ahead removing it.

**Comment by WorldLanguages** [comment]
>  Maybe I would remove the direct link on /welcome first, what do you think?

I forgot about that link! Yeah, let's remove both the page and that link.

**Comment by Hans5958** [comment]
I thought those who have utm_source of extension would mean it is opened from a direct link of the extension, eh?

**Comment by Hans5958** [comment]
I think for now I would remove the link first. Just to make sure...

**Pull request merged**
