### PR TITLE
Refresh of index page (2)

### PR DESCRIPTION
**Pull request by Hans5958**
Sequel to #327. This PR includes day-one fixes regarding to the refresh.

### CODE REVIEW

**Comment by Hans5958** [comment]
@WorldLanguages @BroJac5246 I have removed the Install paragraph for the time being. Any ideas of the replacement, if any?

**Comment by BroJac5246** [comment]
> @ WorldLanguages @ BroJac5246 I have removed the Install paragraph for the time being. Any ideas of the replacement, if any?

It could be something like "Ready to power up Scratch? Install [the extension?/Scratch Addons?] now!"

**Comment by Hans5958** [comment]
> > @ WorldLanguages @ BroJac5246 I have removed the Install paragraph for the time being. Any ideas of the replacement, if any?
> 
> It could be something like "Ready to power up Scratch? Install [the extension?/Scratch Addons?] now!"

Seems nice to me. What do you think, @WorldLanguages?

**Comment by WorldLanguages** [comment]
I think `Ready to power up Scratch?` would be enough.

**Comment by Secret-chest** [comment]
I think that sounds even weirder, maybe `Your Scratch experience will never be the same.`

**Comment by Hans5958** [comment]
This sentence is a [call to action](https://en.wikipedia.org/wiki/Call_to_action_(marketing)), so ideally it should end with a verb. I would try "Ready to power up Scratch? Get it now!" for now. (Install now doesn't look nice with the Install heading)

image

**Comment by Samq64** [comment]
I think upgrade your Scratching experience would sound cool.

**Comment by WorldLanguages** [comment]
> I think upgrade your Scratching experience would sound cool.

That might be hard to translate into other languages.

**Review by WorldLanguages — APPROVED** [review]

**Comment by Hans5958** [comment]
> What tone are we going for actually?

Anything that is related to hook the user, really.

**Pull request merged**
