### PR TITLE
Update welcome page

### PR DESCRIPTION
**Pull request by Hans5958**
I'm clearing the backlog one at the time.

- Update getting started section to reflect latest circumstances (need to click puzzle icon, new version, update images to high quality)
- Add section to pin the extension

@WorldLanguages please improve the wording (if needed)

### CODE REVIEW

**Comment by Hans5958** [comment]
## Preview

**Comment by Samq64** [comment]
Could /addons be linked somewhere? I think that's a better way for new users to discover new addons right now.

**Comment by Hans5958** [comment]
If I have #259 implemented that this is probable, but as the page is limited, linking to `/addons` would not add much value to the user.

**Review by WorldLanguages — APPROVED** [review]
LGTM!

**Pull request merged**
