### PR TITLE
Added image for auto-follow-topics

### PR DESCRIPTION
**Pull request by Waakul**
addon id: ```auto-follow-topics```
addon name ```Follow topics after posting```

### CODE REVIEW

**Comment by Samq64** [comment]
Addon image edits should be kept to a minimum. The second button and arrow are fine but the circle and text seem unnecessary. The image should just be zommed in on the buttons instead.

**Comment by Waakul** [comment]
> Addon image edits should be kept to a minimum. The second button and arrow are fine but the circle and text seem unnecessary. The image should just be zommed in on the buttons instead.

if it's zoomed on the button then it's meaningless as post = follow, so the photo of posting is neccessary.

**Comment by Samq64** [comment]
> if it's zoomed on the button then it's meaningless

Right. Maybe it could show the mouse cursor hovering over the post button?

**Comment by Waakul** [comment]
> > if it's zoomed on the button then it's meaningless
> 
> Right. Maybe it could show the mouse cursor hovering over the post button?

Then it wont follow the post yet?

**Comment by Waakul** [comment]
> > if it's zoomed on the button then it's meaningless
> 
> Right. Maybe it could show the mouse cursor hovering over the post button?

I have a simillar idea, but that'd require alot of editing

**Comment by Waakul** [comment]
auto-follow-topics (3)
Is this ok?

**Comment by Waakul** [comment]
Less edited version of the above
auto-follow-topics (4)

**Comment by Waakul** [comment]
auto-follow-topics (5)
I guess i'll stick with this one

**Comment by Samq64** [comment]
> [auto-follow-topics (5)](https://private-user-images.githubusercontent.com/135821321/311248853-fc2f60fd-29ea-42f1-bb53-df8310c03121.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MDU0MjAsIm5iZiI6MTcwOTkwNTEyMCwicGF0aCI6Ii8xMzU4MjEzMjEvMzExMjQ4ODUzLWZjMmY2MGZkLTI5ZWEtNDJmMS1iYjUzLWRmODMxMGMwMzEyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOFQxMzM4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjJhMzY2ZDAzNDg2YzMyY2QyNTQ1MGY5NzU5NGY5YWJmMjJlNTgwZWNhMDE1NTc0MWQ1NTg4OTU4Mjc4NDhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iRaoPMftn5uOnHxb4uLcEGJ7HsZEpku56ADqDXet7Mc)
> I guess i'll stick with this one

When I said zoomed in I didn't mean that much but that's fine.

**Review by Samq64 — APPROVED** [review]

**Comment by Waakul** [comment]
Is this gonna merge soon?

**Review by Hans5958 — APPROVED** [review]
Really nice. I would say to keep the right arrow on a circle like some of the previous images, but this would do for now.

Also, I saw that your early version and I would like to remind you which where are the image shown, for example, [the Addons page](https://scratchaddons.com/addons/). It wouldn't look nice if one needs to zooms that in by opening the image.

**Comment by Hans5958** [comment]
Related #4

**Pull request merged**
