### PR TITLE
Add some images

### PR DESCRIPTION
**Pull request by mybearworld**
**Add images for:**
- `expanded-backpack`
- `middle-click-popup`
- `opacity-slider`
- `paint-snap`
- `pick-colors-from-stage`
- `share-through-mystuff`
- `sprite-properties`

**Update images for:**
- `hide-project-stats` (addon updated)
- `message-filters` (full coverage of the addon)

### CODE REVIEW

**Comment by Wjplatformer** [comment]
seems ok, but to really show the essence of each addon, the "extended backpack" image should have like a ton of stuff in it, to show that it IS extended. Just a tip, there are other addons like the share from the mystuff, I think it would be more suitable for it to have the title mystuff and a single project shown instead of just 2 words "delete" and "share". Makes it more clearer. 
image

Hope this helps! I can also contribute more images if you ask for them :)

**Comment by Wjplatformer** [comment]
Mostly should be ok if accepted by SA devs.

**Comment by Hans5958** [comment]
Related: #4

**Comment by Hans5958** [comment]
Since I've merged #245 (it came earlier), would you please resolve these conflicts (aka replacing the old with the new or reconsider if needed)? Apologizes.

**Review by Hans5958 — CHANGES_REQUESTED** [review]
Forgot to do this, please read post before

**Comment by mybearworld** [comment]
As far as I can tell, `sprite-properties` was the only conflict - did I miss some?

**Review by Hans5958 — APPROVED** [review]
Yeah. Looks good to me. Thanks!

**Pull request merged**
