### PR TITLE
Adjust highlight style sheets to be closer like GitHub

### PR DESCRIPTION
**Pull request by Hans5958**
The dark highlight style has been replaced to GitHub colors (at least that's what I do the best). There are also minor changes on the light highlight style.

### CODE REVIEW

**Comment by WorldLanguages** [comment]
Before vs after this change:
image

**Comment by WorldLanguages** [comment]
The JS snippet still looks ugly IMO.
The JSON snippet does look better.

**Comment by Hans5958** [comment]
> The JS snippet still looks ugly IMO.

This are actually JavaScript numbers, but the colors would be limited because it is limited by the highlighter.

By the way, I just found out that the highlighter is actually [Chroma](https://github.com/alecthomas/chroma), which is heavily based on Pygments.

**Review by WorldLanguages — APPROVED** [review]
LGTM, looks better than the colors we've used for months

Personally I'd prefer colors closer to the ones from VSCode but this is fine

**Pull request merged**
