### PR TITLE
Redirecting Directories 

### PR DESCRIPTION
**Pull request by LercDsgn**
- This PR adds the following directories: `/chrome `,  `/firefox `,  `/github `,  `/localize `,  `/downloadsource `,  `/youtube `,  `/discord  ` and  `/devdiscord`.
- All files are single tag HTML's.

### CODE REVIEW

**Comment by TheColaber** [comment]
Is there a better way (maybe a Hugo thing) instead of doing it like this

**Comment by WorldLanguages** [comment]
> Is there a better way (maybe a Hugo thing) instead of doing it like this

Probably not

**Comment by LercDsgn** [comment]
Closed until needed & no more efficient alternative found.

**Comment by WorldLanguages** [comment]
> Is there a better way (maybe a Hugo thing) instead of doing it like this

There is now I think

**Comment by RedGuy12** [comment]
I don't really see a point in not keeping it open


________________________________

**Comment by LercDsgn** [comment]
> Closed until no more efficient alternative found.
"Open until no more efficient alternative found" makes more sense, I guess.
>I don't really see a point in not keeping it open
Considering this too

**Review by Wjplatformer — APPROVED** [review]
Since it's already done... might as well merge it. We can implement a better alternative when we find it.

**Comment by Weredime** [comment]
cloudflare page rules? like https://scratchaddons.com/settings

**Comment by RedGuy12** [comment]
there's caps on how many we can make @Weredime

**Comment by WorldLanguages** [comment]
I think Cloudflare added a dedicated feature for redirects, which supports 15 free rules. I'd have to check again to be sure, tho

**Comment by Hans5958** [comment]
Closing in favor of #276.

**Pull request closed without merging**
