### PR TITLE
1.28 addon images

### PR DESCRIPTION
**Pull request by Samq64**
See #4

Adds `find-bar` and `zebra-striping`, updates `editor-devtools`, `cloud-games` and `better-emojis`.

### CODE REVIEW

**Comment by Hans5958** [comment]
Related #4

**Comment by Samq64** [comment]
> ~Related #4~
> 
> I would avoid doing the blue beta thing for cloud games.

It's always blue though... and I bumped to 1.28 stable before taking those screenshots.

**Comment by Hans5958** [comment]
I have to admit I don't touch that addon much. Why there is no "add project" button, again?

**Comment by Samq64** [comment]
> I have to admit I don't touch that addon much. Why there is no "add project" button, again?

The blue only shows up if the game is open and it's already in the list. Otherwise it won't appear at all and the add project will show up instead.

**Comment by Hans5958** [comment]
I see. One part of me said that that is a good addition, but the other part of me said that it would make users confused, like "Why it was blue things on it? Is there something wrong with my installation?"

I guess we can keep the current one for now, if anyone wanted to discuss it, feel free to do so.

**Review by Hans5958 — CHANGES_REQUESTED** [review]
I would say to either (a) separate this PR so it doesn't include future images or (b) hold this until 1.28 launches. It is your preference, but if you do nothing I would do the later.

**Comment by Norbiros** [comment]
If you are in the game it moves it to the top.
If your selected tab is this game, it shows blue color.

**Comment by Hans5958** [comment]
> If you are in the game it moves it to the top. If your selected tab is this game, it shows blue color.

Yeah, I got he said, don't worry about that.

**Review by RedGuy12 — APPROVED** [review]
On `cloud-games`: I think we shouldn't show the blue, but the image should also not have the version number in the screenshot. But that is unrelated to v1.28 so it doesn't need to be done here.

**Comment by Samq64** [comment]
> the image should also not have the version number in the screenshot.

Scratch messaging too?

**Comment by Hans5958** [comment]
To be fair it is fine for me to have the version numbers on those (the images on the index intro also have those), but that's just me.

**Pull request merged**
