### PR TITLE
Header and footer refresh

### LINKED ISSUE #126: Better navbar layout
The current navbar layout is weirdly organized, with the most useful links not being palced first.
I'd suggest changing it to a more conventionnal layout.

## Current:
* language selector
* contributors
* feedback
* repo
* install

## Sugested:
* install (first step to do, so must come 1st)
* addons list (important info, so must come 2nd)
* feedback (happens after install, so 3rd)
* docs (for new users to contribute, isn't required imo but nice to have)
* repo (last important link imo)
* language selector (always last, near the corner)

## Examples
See navbar layout on some random tech websites

<details>
  <summary>Nodejs</summary>

  * home
  * dowloads
  * docs (feature list => same as SA addons list )
  * get involved (to contribute => same as SA  docs)
  * language selector

</details>
<details>
  <summary>SASS</summary>

  * install
  * learn / doc (=> features list => SA addons list)
  * get involved (to contribute => same as SA docs)
</details>
<details>
  <summary>React</summary>

  * docs (=> features list => SA addons list)
  * languages selector
  * repo
</details>
<details>
  <summary>Socket.io</summary>

  * doc / server api / client api (=> features list)
  * comminuty > repo
  * language selector
</details>
<details>
  <summary>RxJS</summary>

  * overview (=> install + features list)
  * reference (=> contribute)
  * repo
</details>
<details>
  <summary>TypeScript</summary>

  * download
  * doc (=> feature list)
  * community > repo
</details>
<details>
  <summary>Jest</summary>

  * docs > install
  * docs > guides (=> features list)
  * language selector
  * repo
</details>

### PR DESCRIPTION
**Pull request by Hans5958**
Resolves #126 

After some polishing, I think it is pretty much done. Any comments are welcome.

### Header
image

### Community dropdown
image

### Footer
image

### CODE REVIEW

**Review by RedGuy12 — CHANGES_REQUESTED** [review]
Two things:

1. https://github.com/ScratchAddons/ScratchAddons/issues/4176#issuecomment-1176939903
> About the last paragraph, we should also use it for the ScratchAddons.com website footer.

2. I think it's important to let people easily access a list of all the features available. The addons list is very hidden in the footer as of now. Please add it to the header.

**Comment by Hans5958** [comment]
I forgot about that disclaimer update so thanks for reminding me about that.

As for the addons page, I'm considering to adding it. I realised this is actually suggested by Ascor before and it is still quite empty after all. For the feedback page I quite disliked the idea to be directly be put on the header again considering that...

1. The community dropdown already has the feedback page on the first item, along with alternatives such as the Discord server and the forum, that we should encourage for better, congregated two-way communication.
2. I'm taking the gamble that we got more people getting it from the extension than from the website header.

**Comment by WorldLanguages** [comment]
> I'm taking the gamble that we got more people getting it from the extension than from the website header.

Well, https://analytics.scratchaddons.com/scratchaddons.com?period=30d&page=%2Ffeedback%2F
image

**Comment by WorldLanguages** [comment]
We should also consider having a visible button that leads the user to Scratch Addons extension settings if the website detects SA is enabled on the device. Currently it won't work for Firefox, but it should work in a few months with manifest V3.

**Comment by Hans5958** [comment]
> We should also consider having a visible button that leads the user to Scratch Addons extension settings if the website detects SA is enabled on the device. Currently it won't work for Firefox, but it should work in a few months with manifest V3.

I could replace the install buttons so it goes to the settings if it got installed, but this would be kind of out of scope since it also edits the index, so I would do this probably later.

**Comment by WorldLanguages** [comment]
> I could replace the install buttons so it goes to the settings if it got installed

Good idea! No reason to show the install button if it's already installed.

**Comment by Wjplatformer** [comment]
@Hans5958 , would you mind showing screenshots of the final navbar layout?

**Comment by Hans5958** [comment]
> @Hans5958 , would you mind showing screenshots of the final navbar layout?

The one on the first message is already been updated with the latest one. Otherwise you can check it yourself.

**Review by Wjplatformer — APPROVED** [review]
Very Good. What I've wanted since I did my first issue here :pleading_face:

**Comment by WorldLanguages** [comment]
LGTM

**Pull request merged**
