### PR TITLE
Add /install

### PR DESCRIPTION
**Pull request by RedGuy12**
Adds a new page that should install to the web store for the user's browser.

### CODE REVIEW

**Comment by RedGuy12** [comment]
I'm not sure how to test this, I don't rant to install Hugo locally and i couldn't get the workflow to work. Plus, I only have access to Edge anyway.

The reason for adding this is because the admins of the Discord server are rewriting #start and we thought it would be a good idea to have links to places like extension stores. This page would be helpful so we don't need to link each store individually.

**Comment by Hans5958** [comment]
Any concrete reason why we need this?

**Comment by Hans5958** [comment]
Related #121

**Comment by RedGuy12** [comment]
> Any concrete reason why we need this?

The admins of the Discord server are currently rewriting #start. We thought it would be a good idea to have links to places like the website and extension stores. This page would be helpful so we don't need to link each store individually. If someone really wants to visit a different store, they can access it through the website.

**Comment by RedGuy12** [comment]
Is this still waiting on anything?

**Comment by RedGuy12** [comment]
@Hans5958 Can this be merged? This is now the only thing blocking implementation of the new rules.

**Comment by Hans5958** [comment]
You got nothing else for this? You can press the merge button.

I got changes but I can hold it for later. Been pretty busy this week.

**Comment by WorldLanguages** [comment]
> I got changes but I can hold it for later.

@Hans5958 this is a reminder (I'm catching up with notifications, and I thought it would be a good idea to remind you in case you forgot, but there's no need to hurry)

**Pull request merged**
